version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./FSSP_site:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: sh -c "cd /app && celery -A FSSP_site worker --loglevel=info"
    volumes:
      - ./FSSP_site:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: sh -c "cd /app && celery -A FSSP_site beat --loglevel=info"
    volumes:
      - ./FSSP_site:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web 