version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./FSSP_site:/app
    environment:
      - DEBUG=1
      - ARBIR_API_KEY=c5ea214946e91d193ab47220c877e435
      - YANDEX_API_KEY=AQVNx5MHmH5Hqfhqm3RIXam8xy1zE3SN1seiCNZF
      - FOLDER_ID=b1gmogi5kl7jvign6303
      - DJANGO_SETTINGS_MODULE=FSSP_site.settings
      - PYTHONPATH=/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: sh -c "cd /app && celery -A FSSP_site worker --loglevel=info"
    volumes:
      - ./FSSP_site:/app
    environment:
      - ARBIR_API_KEY=c5ea214946e91d193ab47220c877e435
      - YANDEX_API_KEY=AQVNx5MHmH5Hqfhqm3RIXam8xy1zE3SN1seiCNZF
      - FOLDER_ID=b1gmogi5kl7jvign6303
      - DJANGO_SETTINGS_MODULE=FSSP_site.settings
      - PYTHONPATH=/app
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: sh -c "cd /app && celery -A FSSP_site beat --loglevel=info"
    volumes:
      - ./FSSP_site:/app
    environment:
      - ARBIR_API_KEY=c5ea214946e91d193ab47220c877e435
      - YANDEX_API_KEY=AQVNx5MHmH5Hqfhqm3RIXam8xy1zE3SN1seiCNZF
      - FOLDER_ID=b1gmogi5kl7jvign6303
      - DJANGO_SETTINGS_MODULE=FSSP_site.settings
      - PYTHONPATH=/app
    depends_on:
      - redis
      - web 