# Generated by Django 4.2.21 on 2025-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название текста')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Текст сайта',
                'verbose_name_plural': 'Тексты сайта',
            },
        ),
    ]
