# Generated by Django 4.2.21 on 2025-05-26 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='URL источника')),
                ('parsed_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Внешний ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актвна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['-parsed_date', 'order'],
                'indexes': [models.Index(fields=['external_id'], name='main_card_externa_943ec3_idx'), models.Index(fields=['parsed_date'], name='main_card_parsed__f33075_idx')],
            },
        ),
    ]
