# Generated by Django 4.2.21 on 2025-05-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_date', models.DateField(verbose_name='Дата для фильтрации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Дата фильтра',
                'verbose_name_plural': 'Даты фильтров',
            },
        ),
    ]
