# Generated by Django 4.2.21 on 2025-05-26 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_filterdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterdate',
            options={'ordering': ['-filter_date'], 'verbose_name': 'Дата фильтрации', 'verbose_name_plural': 'Даты фильтрации'},
        ),
        migrations.AddField(
            model_name='filterdate',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Если отмечено, карточки будут фильтроваться по этой дате', verbose_name='Активный фильтр'),
        ),
        migrations.AlterField(
            model_name='filterdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='filterdate',
            name='filter_date',
            field=models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Дата фильтрации'),
        ),
    ]
