# Generated by Django 5.2.1 on 2025-05-23 13:13

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_card_delete_sitetext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-parsed_date', 'order'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AddField(
            model_name='card',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='card',
            name='parsed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата парсинга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL источника'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['external_id'], name='main_card_externa_943ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['parsed_date'], name='main_card_parsed__f33075_idx'),
        ),
    ]
