# Generated by Django 4.2.21 on 2025-05-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_filterdate_options_filterdate_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
    ]
