# Generated by Django 4.2.21 on 2025-05-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_card_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.TextField(default='aa', verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.TextField(default='aa', verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
