# Generated by Django 4.2.21 on 2025-05-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_card_address_card_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='Name',
        ),
    ]
