# Generated by Django 4.2.21 on 2025-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_address_card_address_rename_name_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(verbose_name='ДатаСоздания'),
        ),
    ]
