# Generated by Django 4.2.21 on 2025-05-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_card_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='parsed_date',
            field=models.DateTimeField(verbose_name='Дата парсинга'),
        ),
    ]
