# Generated by Django 4.2.21 on 2025-05-27 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_card_created_at_alter_card_parsed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='card',
            name='parsed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата парсинга'),
        ),
    ]
